# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'scoke通信' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'CocoaAsyncSocket'	
  # Pods for scoke通信

end
